#!/usr/bin/env node

const got = require('got');

const main = async () => {
    body = await got("https://rb-connect.herokuapp.com");
    console.log("Pinged https://rb-connect.herokuapp.com to keep awake.")
}

main();
